name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Containers
        # We use 'docker compose' (SPACE, NO HYPHEN)
        run: docker compose up -d --build

      - name: Check Container Status
        run: docker compose ps

      - name: View Backend Logs
        # This helps us see if Django actually started
        run: docker compose logs web