name: Django CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Docker
        # NOTICE: This is 'docker compose' (SPACE, NO HYPHEN)
        run: docker compose build

      - name: Up Containers
        run: docker compose up -d